version: "3.3"

services:
  accenture-backend:
    container_name: accenture-backend
    #image: nikosnikolaidis/test_accenture2:2024-04-22
    build:
      context: ./backend/.
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://accenture-db:5432/test_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - '8080:8080'

  accenture-db:
    container_name: accenture-db
    image: postgres:14.7
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'

  accenture-frontend:
    container_name: accenture-frontend
    build:
      context: ./frontend/.
    ports:
      - '80:80'